version: '2'

services:
  airflow:
    container_name: 'airflow'
    image: 'airflow'
    ports:
      - '8080:8080'
    build:
      context: .
      dockerfile: 'Dockerfile'
      args:
        # variables should be in a local .env file which is git ignored
        - AIRFLOW_DB_LISTENADDR=${AIRFLOW_DB_LISTENADDR}
        - AIRFLOW_DB_PORT=${AIRFLOW_DB_PORT}
        - AIRFLOW_DB_USER=${AIRFLOW_DB_USER}
        - AIRFLOW_DB_PASSWORD=${AIRFLOW_DB_PASSWORD}
        - AIRFLOW_DB_NAME=${AIRFLOW_DB_NAME}
        - AIRFLOW_ENCRYPTION_FERNET_KEY=${AIRFLOW_ENCRYPTION_FERNET_KEY}
        - AIRFLOW_ADMIN_USER=${AIRFLOW_ADMIN_USER}
        - AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}

    volumes:
    # volume to share local code folder with container, so we can make changes instantly while developing
      - "./dags:/home/dev/airflow/dags"
  postgres:
    # for Local Executor
    image: 'postgres:13.2-alpine'
    container_name: 'airflow_db'
    ports:
      - '${AIRFLOW_DB_PORT}:${AIRFLOW_DB_PORT}'
    environment:
      - POSTGRES_USER=${AIRFLOW_DB_USER}
      - POSTGRES_PASSWORD=${AIRFLOW_DB_PASSWORD}
      - POSTGRES_LISTENPORT=${AIRFLOW_DB_PORT}
      - POSTGRES_DB=${AIRFLOW_DB_NAME}
