version: "3"

services:
  airflow:
    image: airflow
    container_name: airflow
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "./dags:/airflow/dags"
  postgres:
    image: postgres:13.3-alpine
    container_name: airflow_db
    ports:
      - "${POSTGRES_LISTENPORT}:${POSTGRES_LISTENPORT}"
    env_file:
      - .env
